### ISSUE TITLE
Folder "C:\WinNUT-Client" created at each app launch

### ISSUE THREAD

**Issue by FileCity** [nutdotnet/WinNUT-Client#75] opened 2023-01-29 16:52 UTC
A folder on drive root at "C:\WinNUT-Client" is created at each time the application is started.
Since WinNUT is installed at "C:\Program Files (x86)\WinNUT-client" on my system, this folder on drive root should not be created each time.
Running latest pre-release: 2.2.8359.21169 (from about window).

**Comment by gbakeman** [comment] 2023-02-03 23:09
I think this may be a duplicate of #61. Sorry for taking so long to get another build published, hopefully I'll have one out soon. I'll close this but please let me know if the error is still present after that issue was closed and we can reopen this.

**Closed by gbakeman** 2023-02-03 23:09 UTC
