### ISSUE TITLE
Crash on Connection

### ISSUE THREAD

**Issue by s3dbw** [nutdotnet/WinNUT-Client#94] opened 2023-07-11 17:02 UTC
Latest Beta Version crashing when trying to connect. Crash report uploaded, any thoughts?

Thanks

[Crash Report.txt](https://github.com/nutdotnet/WinNUT-Client/files/12017109/Crash.Report.txt)

**Comment by gbakeman** [comment] 2023-07-11 18:11
It sounds like this issue is a duplicate of #80 , potentially #79 . Please take a look in there for new test builds and see if those help.

**Comment by miles267** [comment] 2023-08-01 02:14
How do you download this debug build?  I'm having same issue on a Windows Server 2019 machine.  Just cannot find the files to download.

**Comment by gbakeman** [comment] 2023-08-01 18:32
@miles267 On the build page [here](https://github.com/nutdotnet/WinNUT-Client/actions/runs/5458178353), at the bottom is an "artifact" which you can download. Extract it and then run the WinNUT executable inside. I hope I can get a new pre-release build up soon so people don't have to download these artifacts.

**Comment by s3dbw** [comment] 2023-08-06 19:05
Latest version v2.2.8617 is working for me, so fix appears to be working, thanks

**Comment by gbakeman** [comment] 2023-08-06 19:48
Thank you for letting me know.

**Closed by gbakeman** 2023-08-06 19:48 UTC
Labels: bug
